---
# Yes, seriously, ubuntu does not install sudo by default.
- name: Installing required tools.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - tar
    - sudo
- name: Upload tar.gz Kibana from local folder
  ansible.builtin.copy:
    src: "{{ kibana_archive }}"
    dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    mode: 0644
    force: true
  register: get_kibana
  until: get_kibana is succeeded
  retries: 3
  delay: 20
  tags: kibana

- name: Create directrory for Kibana
  ansible.builtin.file:
    state: directory
    path: "{{ kibana_home }}"
    mode: 0755
  tags: kibana
- name: Extract Kibana in the installation directory
  become: true
  ansible.builtin.unarchive:
    remote_src: true
    src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    dest: "{{ kibana_home }}"
    mode: 0755
    extra_opts: [--strip-components=1]
    creates: "{{ kibana_home }}/bin/kibana"
  tags: kibana
