---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: docker.io/ubuntu:latest
    pre_build_image: true
  - name: debian
    image: docker.io/pycontribs/debian
    pre_build_image: true
  - name: centos
    image: docker.io/pycontribs/centos:7
    pre_build_image: true    
provisioner:
  name: ansible
verifier:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
lint: |
  set -e
  yamllint .
  ansible-lint .